# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bc48ab8ce5f33813a846c9303393ce38a969422248957a6f5a5ba06c90bbf48e670dc1b8a5d6b115333c71dde69724518d77bb28f69f2b243f92062df5ee5e0

test:
  secret_key_base: f6c3407bbe770dd99c87dc328bd5941bd410d58f13237d95dcf11e4b29e4137fd62611b7566fc330feed1ae8b2b8af33c06d23718059387c8d6cb5045ae12a1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
